services:
  Lab.Auth.AuthRepository:
    class: ../../../../Contexts/Lab/Auth/infrastructure/MongoDBAuthRepository
    arguments: []

  Lab.Auth.AuthCommandCreator:
    class: ../../../../Contexts/Lab/Auth/application/AuthCommandCreator
    arguments: ["@Lab.Auth.AuthRepository"]

  Lab.Auth.AuthQueryCreator:
    class: ../../../../Contexts/Lab/Auth/application/AuthQueryCreator
    arguments: ["@Lab.Auth.AuthRepository"]

  Lab.shared.Logger:
    class: ../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Apps.Lab_backend.controllers.AuthPutController:
    class: ../../controllers/AuthPutController
    arguments: ["@Lab.Auth.AuthCommandCreator"]

  Apps.Lab_backend.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: ["@Lab.Auth.AuthQueryCreator"]
